IF OBJECT_ID('School', N'U') IS NULL
BEGIN
	CREATE TABLE School
	(
		Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
		[Name] NCHAR(255) NOT NULL, 
		[Number] CHAR(10),
		[Phone] CHAR(10) NOT NULL
		CONSTRAINT UQ_School_Number UNIQUE ([Number])
	);
END
GO

IF OBJECT_ID(N'Class', N'U') IS NULL
BEGIN
	CREATE TABLE Class
	(
		Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
		[Name] NCHAR(3) NOT NULL,
		SchoolId INT NOT NULL,
		CONSTRAINT UQ_Class_Name UNIQUE ([Name], SchoolId),
		CONSTRAINT FK_Class_SchoolId FOREIGN KEY (SchoolId) REFERENCES School(Id) ON DELETE CASCADE ON UPDATE CASCADE
	);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [Name]= N'IX_CLASS_SCHOOL' AND object_id = OBJECT_ID(N'Class', N'U'))
BEGIN
	CREATE NONCLUSTERED INDEX IX_CLASS_SCHOOL ON Class(SchoolId);
END

IF OBJECT_ID('Student','U') IS NULL
BEGIN
	CREATE TABLE Student
	(
		Id INT PRIMARY KEY IDENTITY(1, 1),
		[FirstName] NCHAR(50) NOT NULL,
		[LastName] NCHAR(50) NOT NULL,
		[Patronymic] NCHAR(50) NOT NULL,
		[Phone] CHAR(10) NOT NULL,
		ClassId INT NOT NULL FOREIGN KEY REFERENCES Class(Id) ON DELETE CASCADE ON UPDATE CASCADE
	);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [Name]= N'IX_Student_Class' AND object_id = OBJECT_ID(N'Student', N'U'))
BEGIN
	CREATE NONCLUSTERED INDEX IX_Student_Class ON Student(ClassId);
END
GO
